[dns]
no-system
no-ipv6
doh-server = https://cloudflare-dns.com/dns-query
server=/*.cn/system
server=/*.alicdn.com/system
server=/*.taobao.com/system
server=/*.tmall.com/system
server=/*.alipay.com/system
server=/*.alipayobjects.com/system
server=/*.aliyun.com/system
server=/*.xianyu.com/system
server=/*.fliggy.com/system
server=/*.qq.com/system
server=/*.tencent.com/system
server=/*.weixin.com/system
server=/*.qpic.cn/system
server=/*.qlogo.cn/system
server=/*.gtimg.com/system
server=/*.baidu.com/system
server=/*.bdstatic.com/system
server=/*.bcebos.com/system
server=/*.amap.com/system
server=/*.autonavi.com/system
server=/*.12306.cn/system
server=/*.58.com/system
server=/*.didiglobal.com/system
server=/*.didichuxing.com/system
server=/*.jd.com/system
server=/*.360buyimg.com/system
server=/*.jdpay.com/system
server=/*.bilibili.com/system
server=/*.hdslb.com/system
server=/*.bytedance.com/system
server=/*.byteimg.com/system
server=/*.toutiao.com/system
server=/*.pstatp.com/system
server=/*.snssdk.com/system
server=/*.volces.com/system
server=/*.yangkeduo.com/system
server=/*.pinduoduo.com/system
server=/*.pddpic.com/system
server=/*.meituan.com/system
server=/*.dianping.com/system
server=/*.qianji.space/system
server=/*.10086.cn/system
server=/*.weibo.com/system
server=/*.sinaimg.cn/system
server=/*.nga.cn/system
server=/*.ngacn.cc/system
server=/*.ciweimao.com/system
server=/*.hbooker.com/system
server=/*.powerchina.cn/system
server=/*.fj.gov.cn/system
server=/*.fuzhou.gov.cn/system
server=/*.chinatax.gov.cn/system
server=/*.unionpay.com/system
server=/*.unionpaysecure.com/system
server=/*.netsunion.com.cn/system
server=/*.icbc.com.cn/system
server=/*.abchina.com/system
server=/*.boc.cn/system
server=/*.ccb.com/system
server=/*.bankcomm.com/system
server=/*.psbc.com/system
server=/*.cmbchina.com/system
server=/*.citicbank.com/system
server=/*.cebbank.com/system
server=/*.cib.com.cn/system
server=/*.spdb.com.cn/system
server=/*.cmbc.com.cn/system
server=/*.gdb.com.cn/system
server=/*.pingan.com/system
server=/*.hxb.com.cn/system
server=/*.hxbc.com.cn/system
server=/*.czbank.com/system
server=/*.ebank.sdb.com.cn/system
server=/*.srcb.com/system
