[dns]
circumvent-ipv4-answer = 127.0.0.1, 0.0.0.0
no-system
no-ipv6
doh-server = https://cloudflare-dns.com/dns-query
server=/*.cn/system
server=/*.alicdn.com/system
server=/*.taobao.com/system
server=/*.tmall.com/system
server=/*.alipay.com/system
server=/*.alipayobjects.com/system
server=/*.aliyun.com/system
server=/*.xianyu.com/system
server=/*.fliggy.com/system
server=/*.qq.com/system
server=/*.tencent.com/system
server=/*.tencent-cloud.net/system
server=/*.weixin.com/system
server=/*.qpic.cn/system
server=/*.qlogo.cn/system
server=/*.gtimg.com/system
server=/*.baidu.com/system
server=/*.bdstatic.com/system
server=/*.bcebos.com/system
server=/*.amap.com/system
server=/*.autonavi.com/system
server=/*.58.com/system
server=/*.didiglobal.com/system
server=/*.didichuxing.com/system
server=/*.jd.com/system
server=/*.360buyimg.com/system
server=/*.jdpay.com/system
server=/*.bilibili.com/system
server=/*.hdslb.com/system
server=/*.bytedance.com/system
server=/*.byteimg.com/system
server=/*.toutiao.com/system
server=/*.pstatp.com/system
server=/*.snssdk.com/system
server=/*.volces.com/system
server=/*.yangkeduo.com/system
server=/*.pinduoduo.com/system
server=/*.pddpic.com/system
server=/*.meituan.com/system
server=/*.dianping.com/system
server=/*.qianji.space/system
server=/*.weibo.com/system
server=/*.ngacn.cc/system
server=/*.ciweimao.com/system
server=/*.hbooker.com/system
server=/*.unionpay.com/system
server=/*.unionpaysecure.com/system
server=/*.abchina.com/system
server=/*.ccb.com/system
server=/*.bankcomm.com/system
server=/*.psbc.com/system
server=/*.cmbchina.com/system
server=/*.citicbank.com/system
server=/*.cebbank.com/system
server=/*.pingan.com/system
server=/*.czbank.com/system
server=/*.srcb.com/system
server=/*.apple.com/system
server=/*.icloud.com/system
