[dns]
circumvent-ipv4-answer = 127.0.0.1, 0.0.0.0
no-system
no-ipv6
doh-server = https://cloudflare-dns.com/dns-query
server=/*.cn/system
server=/*.alicdn.com/system
server=/*.alipay.com/system
server=/*.alipayobjects.com/system
server=/*.aliyun.com/system
server=/*.aliyuncs.com/system
server=/*.alibaba.com/system
server=/*.alibabachengdun.com/system
server=/*.alibaba.com/system
server=/*.taobao.com/system
server=/*.tmall.com/system

server=/*.xianyu.com/system
server=/*.fliggy.com/system
server=/*.qq.com/system
server=/*.tencent.com/system
server=/*.tencent-cloud.net/system
server=/*.weixin.com/system
server=/*.qpic.cn/system
server=/*.qlogo.cn/system
server=/*.gtimg.com/system
server=/*.baidu.com/system
server=/*.bdstatic.com/system
server=/*.bdimg.com/system
server=/*.bcebos.com/system
server=/*.amap.com/system
server=/*.autonavi.com/system
server=/*.58.com/system
server=/*.didiglobal.com/system
server=/*.didichuxing.com/system
server=/*.jd.com/system
server=/*.360buyimg.com/system
server=/*.jdpay.com/system
server=/*.bilibili.com/system
server=/*.hdslb.com/system
server=/*.bytedance.com/system
server=/*.byteimg.com/system
server=/*.toutiao.com/system
server=/*.pangolin-sdk-toutiao.com/system
server=/*.pstatp.com/system
server=/*.snssdk.com/system
server=/*.volces.com/system
server=/*.yangkeduo.com/system
server=/*.pinduoduo.com/system
server=/*.pddpic.com/system
server=/*.meituan.com/system
server=/*.dianping.com/system
server=/*.qianji.space/system
server=/*.weibo.com/system
server=/*.ngacn.cc/system
server=/*.ciweimao.com/system
server=/*.hbooker.com/system
server=/*.unionpay.com/system
server=/*.unionpaysecure.com/system
server=/*.abchina.com/system
server=/*.ccb.com/system
server=/*.bankcomm.com/system
server=/*.psbc.com/system
server=/*.cmbchina.com/system
server=/*.citicbank.com/system
server=/*.cebbank.com/system
server=/*.pingan.com/system
server=/*.czbank.com/system
server=/*.srcb.com/system
server=/*.apple.com/system
server=/*.apple-mapkit.com/system
server=/*.icloud.com/system
server=/*.huawei.com/system
server=/*.windows.net/system
server=/*.mzstatic.com/system
server=/*.izazamall.com/system
server=/*.doubleclick-cn.net/system
server=/*.ajkimg.net/system
server=/*.getui.net/system
server=/*.anjuke.com/system
server=/*.youku.com/system
server=/*.xiaojukeji.com/system
server=/*.udache.com/system
server=/*.didistatic.com/system
server=/*.yunxish.com/system
server=/*.zztfly.com/system
server=/*.my-imcloud.com/system
server=/*.qcloud.com/system
server=/*.webank.com/system
server=/*.tctpwebank.com/system
server=/*.webankwealth.com/system
server=/*.95516.com/system
server=/*.nuomi.com/system
server=/*.xiaohongshu.com/system
server=/*.xhscdn.com/system
